version: '3.7'
services:
  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'
  worker:
    build:
      context: worker
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
  queue-wrapper:
    build:
      context: queue-wrapper
    depends_on:
      - "redis"
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'
  web-page:
    build:
      context: web-page
    depends_on:
      - queue-wrapper
    ports:
      - '9780:9780'

networks:
    default:
        external:
            name: videothumbnail
